name: Hooks Workflows
run-name: action ${{github.run_number}}

on:
  push:
    branches:
      - "main"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repos
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Build and Push to Dockerhub
        uses: docker/build-push-action@v5

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.HOOKS_TOKEN}}
          publish_dir: ./dist